[package]
name = "anycms-spa"
version = "0.7.1"
edition = "2024"

authors = ["Liangdi<wu@liangid.me>"]
description = "SPA integration with Web Frameworks"
keywords = ["anycms","spa","actix-web","axum","salvo"]
homepage = "https://anycms.org"
repository = "https://github.com/anycms/anycms-spa"
license = "MIT"

[dependencies]
actix-web = {version = "4.14.1",optional = true}
axum = {version = "0.8.9",optional = true}
mime_guess = "2.0.5"
paste = "1.0.15"
rust-embed = "8.12.0"
salvo = {version = "0.95.2",optional = true}
thiserror = "2.0.20"
tracing = "0.1.44"
flate2 = { version = "1", optional = true }
brotli = { version = "8", optional = true }
sha2 = "0.11"

[features]
default = []
actix = ["dep:actix-web"]
axum = ["dep:axum"]
salvo = ["dep:salvo"]
gzip = ["dep:flate2"]
brotli = ["dep:brotli"]
